### ISSUE TITLE
feat: let the users view the rating page without having to log in

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#42]
This is a follow-up idea to the #37 and should be done after it is merged.

**Comment by ishitab02** [comment]
hey, can you assign this to me?

**Comment by yurijmikhalevich** [comment]
@ishitab02, hi! Sorry for the delayed response. Let me know if you still want to work on this.

**Comment by arilloid** [comment]
Hello @yurijmikhalevich,

I'd love to contribute to Aibyss, the concept of the game sounds very fun!
Can I take this issue?/Would you recommend any other existing issues for newcomers?

**Comment by yurijmikhalevich** [comment]
Hi @arilloid! 👋 

Thank you for reaching out! Yes, of course, you can take this issue! It's a good one to start with. It should take a smaller change to the `PUBLIC_PATHS` in `server/middleware/auth.ts`, and let's move the "rating" link to the header so it's accessible from any page. Let me know if you have any questions!

**Comment by arilloid** [comment]
@yurijmikhalevich 

Thank you! 
I will look into it and let you know if I have any doubts

**Comment by yurijmikhalevich** [comment]
Done in #90
