### ISSUE TITLE
feat: add ability to view the current game without having to log in

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#43]
Display the current game at the login screen.

E.g. we should update the login screen to look exactly like the screen after login, but instead of the code editor, we should display the login form.

**Comment by mahenoorsalat** [comment]
Assign me this .. I will look out this issues @yurijmikhalevich

**Comment by yurijmikhalevich** [comment]
@mahenoorsalat, assigned. Thank you for taking it! 😄

**Comment by yurijmikhalevich** [comment]
For this one, we need to:
- allow users to request /api/state without authorization
- add the GameScreen to the right of the login form on the login page

**Comment by yurijmikhalevich** [comment]
@mahenoorsalat, I have unassigned you from the issue. Let me know if you still want to work on it.

**Comment by mahenoorsalat** [comment]
yeah I am willing to .. but aren't you talking like you have to update something .. so when it done ? just comment it here :) @yurijmikhalevich

**Comment by yurijmikhalevich** [comment]
@mahenoorsalat, yes, right now, we want to make a few important changes before thinking about further design improvements! Thank you for reaching out!

**Comment by arilloid** [comment]
Hello @yurijmikhalevich!

Thank you for the prompt feedback on my PR! 
Leaving the comment here to be able to pick up this issue 😊

**Comment by yurijmikhalevich** [comment]
@arilloid, thank you! Assigned.

Let's make it look like the game page (we should reuse the page or the components) but without the code.

In place of the code, let's display the login form.

<img width="1608" alt="Screenshot 2024-12-08 at 16 52 45" src="https://github.com/user-attachments/assets/58342e62-7ae0-4b6f-9a21-d702aa378e5c">

**Comment by yurijmikhalevich** [comment]
Done in #92
