### ISSUE TITLE
feat: add onboarding with tutorials

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#45]
Before implementing, please share your ideas with me and make sure that we are aligned on them.

**Comment by naaa760** [comment]
Hello @yurijmikhalevich 

Please, provide enough information for this enhancement, so click Get an idea of what to implement.

**Comment by yurijmikhalevich** [comment]
@naaa760, hi! The best will be to start with some exploratory work:
- setup & launch the project locally
- think about how the onboarding may look like
- share a proposal draft (maybe, in Figma)

**Comment by naaa760** [comment]
You are talking about User onboarding with tutorials?  
Like how to build a community platform with a focus on User onboarding.

**Comment by yurijmikhalevich** [comment]
@naaa760, I am talking about user onboarding to the Aibyss game. In the onboarding, we should teach them:
- how Aibyss works
- how to write simple programs to control the bot
- maybe, have them do some exercises, like finishing a maze, that will require them to write a program to control the bot

**Comment by naaa760** [comment]
I will be sharing a proposal draft in Figma. 
That would be okay!

**Comment by yurijmikhalevich** [comment]
@naaa760, this would be 🔥 Thank you!

**Comment by naaa760** [comment]
would you mind, if I share here the link to Figma?

**Comment by yurijmikhalevich** [comment]
@naaa760, of course. Thank you!

**Comment by yurijmikhalevich** [comment]
Closing this because this didn't come up during our second internal tournament.
