### ISSUE TITLE
feat: zoom in on the game screen to show the players bot more closely

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#48]

**Comment by aldrin312** [comment]
Can I get assigned for this issue?

**Comment by yurijmikhalevich** [comment]
@aldrin312, 👋  thank you for reaching out! I have already assigned #50 to you, and we usually take tasks one at a time. Doing this lets us stay focused and enables others to grab tasks that aren't being actively worked on at the moment 😄 Let's do #50 first. After this, you can take this one unless someone else gets to it before then.

**Comment by aldrin312** [comment]
Sorry I thought this was easy to implement that I can do a pull request together with #50. 
I'll finish issue #50 first.

**Comment by aldrin312** [comment]
May I work on this next?

**Comment by yurijmikhalevich** [comment]
@aldrin312, of course! I am not completely sure how exactly this one should look like. Hopefully, you are open to iterate a bit on the implementation.

I think, for this one, we want:
a) a minimap in the bottom right corner showing the whole game – it should be reasonably sized to see everything
b) the main screen should show the game screen somewhat zoomed in on the player

Maybe, we should also keep an option to "zoom out" and get back to the current mode by pressing a button.

**Comment by aldrin312** [comment]
My first thought was using a the scroll wheel to zoom in on the point where the mouse currently is on the canvas.

**Comment by aldrin312** [comment]
![Recording 2024-11-20 at 18 09 06](https://github.com/user-attachments/assets/eaf98ac2-c538-4be0-abe9-d6da9676eec6)
This is what I have so far.
Currently its zooms in on mouse wheel, I'll change it to a button later if that's more preferred.
I will also make it follow the player on zoom in.

**Comment by yurijmikhalevich** [comment]
@aldrin312, this looks pretty cool! 🔥 

I think that following the player while zoomed in is important. It's up to you how to implement it; potentially we can have 3 modes:
1. zoomed out (like it is now on `main`)
2. zoomed in with the wheel – the user can explore the map freely
3. zoomed in "follow" mode – in this mode, we determine the level of zoom automatically and follow the player

The "follow" mode can be triggered via a button, and the user can get out of it by either:
- zooming with the mouse wheel – user transitions into the mode 2
- moving the map with the mouse – user transitions into the mode 2
- clicking a button – user transitions into the mode 1

If you want, we can merge the mouse wheel zoom (mode 2) first.

What do you think?

By the way, is it possible for me to "move" the map by dragging when I am zoomed in? This would be very cool.

**Comment by aldrin312** [comment]
I'll see what I can do on implementing the 3 modes and I do want it to be able to be draggable on mouse down when zoomed in, but I'm not sure how to do that yet.

Though I think its better if mode 2 instead it let user zoom in with mouse wheel on mouse location so that they can explore the map freely by dragging the map. I'll try making a pull request for this one first and then the follow button after.

**Comment by yurijmikhalevich** [comment]
@aldrin312, sounds good. Thank you.

> I think its better if mode 2 instead it let user zoom in with mouse wheel on mouse location so that they can explore the map freely by dragging the map

Yes, this is what I am thinking too about the "mode 2."

**Comment by yurijmikhalevich** [comment]
closed by #81
