### ISSUE TITLE
feat: allow resizing the code editor and the game screen by dragging the separator between them

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#50]

**Comment by aldrin312** [comment]
Can I get assigned for this issue?

**Comment by yurijmikhalevich** [comment]
@aldrin312, of course. Thank you for reaching out! 🙌 

Let me know if you have any questions.

**Comment by aldrin312** [comment]
Is this acceptable?
![Recording 2024-11-15 at 12 58 39](https://github.com/user-attachments/assets/57af662a-6a30-4ee1-a3a2-f1ad8d8820d8)

**Comment by yurijmikhalevich** [comment]
@aldrin312, thank you for putting it up quickly 🙌 

Let's avoid introducing horizontal scrolling.

<img width="847" alt="Screenshot 2024-11-16 at 09 15 29" src="https://github.com/user-attachments/assets/686b7f80-8130-4763-b3e8-12df1d8ba2fc">

**Comment by aldrin312** [comment]
Oh yes I plan to remove those.
But for the main feature, is their any concern on it?

**Comment by yurijmikhalevich** [comment]
@aldrin312, let's add some limits so I can't absolutely collapse the game screen. Otherwise, it looks good. Thank you 🙌

**Comment by yurijmikhalevich** [comment]
Done in #78. Thank you @aldrin312! 🔥
