### ISSUE TITLE
exploration: explore the login & signup form designs in figma

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/aibyss#52]
Related ticket: https://github.com/move-fast-and-break-things/aibyss/issues/43.

But we don't necessarily have to follow the designs described in the other ticket, I am open to exploring other options.

**Comment by mahenoorsalat** [comment]
sure will create one @yurijmikhalevich  ! assign me this sir,

**Comment by yurijmikhalevich** [comment]
@mahenoorsalat, thank you for reaching out! Assigned :)
