### ISSUE TITLE
feat: add a button where it would zoom in closely to the bot and follows it.

### ISSUE THREAD

**Issue by aldrin312** [move-fast-and-break-things/aibyss#84]
Description:

- Pressing the button allows users to zoom in closely on a bot and continuously follow its movements. 
- Pressing it again will return to regular map view.
- Zooming in and following must remain in the constraint of the map.

**Comment by aldrin312** [comment]
Can I get assigned for this?

**Comment by yurijmikhalevich** [comment]
@aldrin312, of course! Assigned. Thank you! 😄

**Comment by yurijmikhalevich** [comment]
@aldrin312, do you want to play Aibyss with us? 😄 Email me at yurij@mikhalevi.ch if you do 😄

**Comment by aldrin312** [comment]
Sadly I can't I'm busy today.

**Comment by yurijmikhalevich** [comment]
@aldrin312, sure! And no rush to join! We are doing a small tournament this Sunday, and it's also an ongoing thing we have – the bots compete even if you aren't looking at them 😆

**Comment by aldrin312** [comment]
That's cool. I'll try joining if I can.

**Comment by aldrin312** [comment]
any suggestion on what the button should look like and where it should be for now?

**Comment by yurijmikhalevich** [comment]
@aldrin312, maybe we should add it above the game screen? In the same panel where the `rating` link is? We can use `ButtonLink` for it, and improve the styles later/in a follow up, if needed?

**Comment by yurijmikhalevich** [comment]
Closed by #89
